// AppleFlavorCounter.jsx
import React, { useState, useEffect, useLayoutEffect, useRef, useMemo } from 'react';
import { gsap } from 'gsap';

const Digit = ({ value, prevValue }) => {
  const containerRef = useRef(null);
  const currentRef = useRef(null);
  const isFirstRender = useRef(true);

  useLayoutEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      return;
    }
    
    // If value hasn't effectively changed (e.g. from parent re-render but same prop), skip
    if (value === prevValue) return;

    const el = currentRef.current;
    const container = containerRef.current;

    // Create a clone for the exiting digit (the OLD value)
    const oldEl = document.createElement('div');
    oldEl.textContent = prevValue;
    
    // Copy computed styles to ensure identical appearance
    const computedStyle = window.getComputedStyle(el);
    oldEl.style.cssText = computedStyle.cssText;
    
    // Override positioning for the clone to sit on top
    oldEl.style.position = 'absolute';
    oldEl.style.top = '0';
    oldEl.style.left = '0';
    oldEl.style.margin = '0'; // Reset margin if any
    oldEl.style.transform = 'none'; // Reset transform if any on parent
    
    container.appendChild(oldEl);

    // Direction Logic:
    // "When new < old ... appear from below ... cover old value"
    // "When old is 0, treat as 10"
    
    let effectiveOld = prevValue;
    if (prevValue === 0) effectiveOld = 10;
    
    // Comparison for direction
    // If new < effectiveOld: Enter from BOTTOM (translateY: 100% -> 0%)
    // If new > effectiveOld: Enter from TOP (translateY: -100% -> 0%)
    const isNewSmaller = value < effectiveOld;
    
    const enterFrom = isNewSmaller ? '100%' : '-100%';
    const exitTo = isNewSmaller ? '-100%' : '100%'; // Opposite direction exit

    // Animate New Digit (Enter)
    gsap.fromTo(el,
      { y: enterFrom, opacity: 0, filter: 'blur(10px)' },
      { y: '0%', opacity: 1, filter: 'blur(0px)', duration: 0.5, ease: 'power2.out' }
    );

    // Animate Old Digit (Exit)
    gsap.fromTo(oldEl,
      { y: '0%', opacity: 1, filter: 'blur(0px)' },
      { 
        y: exitTo, 
        opacity: 0, 
        filter: 'blur(10px)', 
        duration: 0.5, 
        ease: 'power2.out', 
        onComplete: () => {
          if (oldEl.parentNode) oldEl.parentNode.removeChild(oldEl);
        }
      }
    );

  }, [value, prevValue]);

  return (
    <div ref={containerRef} style={{ position: 'relative', width: '0.6em', height: '1.2em', overflow: 'hidden', display: 'inline-block' }}>
      <div ref={currentRef} style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        {value}
      </div>
    </div>
  );
};

export default function AppleFlavorCounter({ className, style }) {
  const [inputValue, setInputValue] = useState(0);
  const [debouncedValue, setDebouncedValue] = useState(0);
  const [debounceTime, setDebounceTime] = useState(300);
  const [displayDigits, setDisplayDigits] = useState([]);
  const [prevDigits, setPrevDigits] = useState([]);
  
  // Debounce Logic
  useEffect(() => {
    const delay = (debounceTime === '' || isNaN(debounceTime)) ? 300 : debounceTime;
    const handler = setTimeout(() => {
      setDebouncedValue(inputValue);
    }, delay);
    return () => clearTimeout(handler);
  }, [inputValue, debounceTime]);

  // Refined Logic for Digits
  const prevValueRef = useRef(0);
  
  useEffect(() => {
    // Current (New)
    const currentStr = String(debouncedValue);
    // Previous (Old)
    const prevStr = String(prevValueRef.current);
    
    const maxLength = Math.max(currentStr.length, prevStr.length);
    
    const paddedCurrent = currentStr.padStart(maxLength, '0');
    const paddedPrev = prevStr.padStart(maxLength, '0');
    
    const newArr = paddedCurrent.split('').map(Number);
    const oldArr = paddedPrev.split('').map(Number);
    
    setDisplayDigits(newArr);
    setPrevDigits(oldArr);
    
    prevValueRef.current = debouncedValue;
  }, [debouncedValue]);

  return (
    <div className={className} style={{ padding: '40px', fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif', ...style }}>
      <div style={{ marginBottom: '40px', display: 'flex', flexDirection: 'column', gap: '10px', maxWidth: '300px' }}>
        <label>
          Number:
          <input 
            type="number" 
            value={inputValue}
            onChange={(e) => setInputValue(parseInt(e.target.value) || 0)}
            style={{ marginLeft: '10px', padding: '5px' }}
          />
        </label>
        <label>
          Debounce (ms):
          <input 
            type="number" 
            value={debounceTime}
            onChange={(e) => setDebounceTime(parseInt(e.target.value) || 300)}
            style={{ marginLeft: '10px', padding: '5px' }}
          />
        </label>
      </div>

      <div className="flavor-counter" style={{ 
        display: 'flex', 
        fontSize: '8rem', 
        fontWeight: '800', 
        lineHeight: 1,
        color: 'inherit' // Inherit color from parent
      }}>
        {displayDigits.map((digit, i) => (
          <Digit 
            key={i} 
            value={digit} 
            prevValue={prevDigits[i]} 
          />
        ))}
      </div>
    </div>
  );
}

// src/AppleFlavorCounter.vue
<template>
  <div
    ref="counterRef"
    class="apple-counter"
    :style="{ fontSize: size + 'px', color: color }"
  >
    <div
      v-for="(digitState, index) in displayDigits"
      :key="index"
      class="digit-slot"
    >
      <span v-if="digitState.old !== null" class="digit old">
        {{ digitState.old }}
      </span>

      <span class="digit new">
        {{ digitState.current }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick, onMounted, useTemplateRef } from 'vue'
import gsap from 'gsap'

const props = defineProps({
  modelValue: {
    type: Number,
    required: true
  },
  debounce: {
    type: Number,
    default: 300
  },
  size: {
    type: Number,
    default: 48
  },
  color: {
    type: String,
    default: 'inherit'
  }
})

interface DigitState {
  current: string
  old: string | null
  direction: 'from-bottom' | 'from-top' | null
}

const counterRef = useTemplateRef<HTMLDivElement>('counterRef')
const displayDigits = ref<DigitState[]>([])

let timeoutId: ReturnType<typeof setTimeout> | null = null
let lastStableValue = props.modelValue

onMounted(() => {
  const str = props.modelValue.toString().split('')
  displayDigits.value = str.map(d => ({
    current: d,
    old: null,
    direction: null
  }))
})

const updateCounter = (newValue: number) => {
  const oldValue = lastStableValue

  let newStr = newValue.toString()
  let oldStr = oldValue.toString()
  const maxLength = Math.max(newStr.length, oldStr.length)

  newStr = newStr.padStart(maxLength, '0')
  oldStr = oldStr.padStart(maxLength, '0')

  const newArr = newStr.split('')
  const oldArr = oldStr.split('')

  const nextState: DigitState[] = newArr.map((digit, index) => {
    const oldDigit = oldArr[index]

    if (digit === oldDigit) {
      return { current: digit, old: null, direction: null }
    }

    const n = parseInt(digit)
    const o = parseInt(oldDigit)
    const direction = n < o ? 'from-bottom' : 'from-top'

    return {
      current: digit,
      old: oldDigit,
      direction: direction
    }
  })

  displayDigits.value = nextState
  lastStableValue = newValue

  nextTick(() => {
    if (!counterRef.value) return

    const slots = counterRef.value.querySelectorAll('.digit-slot')

    slots.forEach((slot, index) => {
      const state = displayDigits.value[index]
      if (!state || !state.old) return

      const oldEl = slot.querySelector('.old')
      const newEl = slot.querySelector('.new')

      if (oldEl && newEl) {
        const isFromBottom = state.direction === 'from-bottom'
        const yOffset = 100

        gsap.killTweensOf([oldEl, newEl])

        gsap.fromTo(
          oldEl,
          {
            yPercent: 0,
            opacity: 1,
            filter: 'blur(0px)'
          },
          {
            yPercent: isFromBottom ? -yOffset : yOffset,
            opacity: 0,
            filter: 'blur(10px)',
            duration: 0.5,
            ease: 'power2.out'
          }
        )

        gsap.fromTo(
          newEl,
          {
            yPercent: isFromBottom ? yOffset : -yOffset,
            opacity: 0,
            filter: 'blur(10px)'
          },
          {
            yPercent: 0,
            opacity: 1,
            filter: 'blur(0px)',
            duration: 0.5,
            ease: 'power2.out'
          }
        )
      }
    })
  })
}

watch(
  () => props.modelValue,
  newVal => {
    if (timeoutId) clearTimeout(timeoutId)

    if (!props.debounce) {
      updateCounter(newVal)
      return
    }

    timeoutId = setTimeout(() => {
      updateCounter(newVal)
    }, props.debounce)
  }
)
</script>

<style scoped>
.apple-counter {
  display: inline-flex;
  font-feature-settings: 'tnum'; /* 等宽数字，防止抖动 */
  font-variant-numeric: tabular-nums;
  overflow: hidden;
  line-height: 1;
}

.digit-slot {
  position: relative;
  display: inline-block;
  width: 0.6em; /* 根据字体调整宽度 */
  height: 1em;
  text-align: center;
}

.digit {
  display: inline-block;
  width: 100%;
  height: 100%;
  /* 确保新旧数字重叠 */
}

.digit.new {
  position: relative; /* 默认流 */
  z-index: 2;
}

.digit.old {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1;
}
</style>
